version: '3.7'

services:
  web:
    build: .
    command: gunicorn django_todo_app.wsgi -b 0.0.0.0:8000
    # (pseudo SECRET_KEY)
    environment: 
      - ENVIRONMENT=production
      - SECRET_KEY=(8b&dzzbui0hpinot&xvj5e94q=01y43w_dg=3*13sewx2&np5 
      - DEBUG=0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11