version: '3.7'

services:
  web:
    build: .
    command: gunicorn django_todo_app.wsgi -b 0.0.0.0:8000
    # (pseudo SECRET_KEY)
    environment: 
      - ENVIRONMENT=development
      - SECRET_KEY=(8b&dzzbui0hpinot&xvj5e94q=01y43w_dg=3*13sewx2&np5
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: