# Generated by Django 3.0.7 on 2020-06-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.TimeField(auto_now_add=True)),
                ('due_date', models.TimeField()),
                ('priority', models.IntegerField(choices=[(1, 'Vital'), (2, 'Important'), (3, 'Urgent'), (4, 'Trivial')])),
                ('tags', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase', models.BooleanField()),
                ('estimated_time', models.IntegerField(max_length=4)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
