# Generated by Django 3.0.7 on 2020-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='estimated_time',
            field=models.IntegerField(),
        ),
    ]
