# Generated by Django 3.0.7 on 2020-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200604_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
