# Generated by Django 3.0.7 on 2020-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200604_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Vital'), (2, 'Important'), (3, 'Urgent'), (4, 'Trivial')], default=4),
        ),
    ]
