# Generated by Django 3.0.7 on 2020-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20200604_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='todo',
            name='purchase',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
