# Generated by Django 3.0.7 on 2020-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20200605_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
