# Generated by Django 3.0.7 on 2020-06-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20200605_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='estimated_time',
            new_name='duration',
        ),
    ]
